import Head from 'next/head';
import Link from 'next/link';
import Styles from '../Styles/home.module.css';
export default function Home() {
  return (
    <>
      <Head>
        <title>Numerology | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* class="image-container" */}
      <div className={Styles.image_container}>
        <img
          src="https://assets.nicepagecdn.com/d2cc3eaa/378349/images/spiritual-prayer-hands-holding-bible3.jpg"
          alt="Image"
        />
        <Link href="/numerology">
          <button className={Styles.overlay_button}>
            DOB / Name Numerology
          </button>
        </Link>
      </div>
    </>
  );
}
